### ISSUE TITLE
Desktop - design - pagina programs and networks

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#103]
https://elaborate-frangipane-2705dc.netlify.app/programs-and-networks/

Revisar esta pagina

1. veo titulo y texto en dos columnas
![Captura de pantalla 2023-05-17 a las 11 55 13](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/33a72f2e-cff6-473c-98b7-b2fc2c847316)

2. las cajas deberian tener la misma altura basada en el mas alto de los hermanos
3. Las cajas deberian soportar los nuevos colores definidos en la otra tarea
4. La imagen de fondo deberia ser cover para que no se repita
![Captura de pantalla 2023-05-17 a las 11 56 41](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/0311b0f9-d59e-4011-90cb-3e2f2f489553)

**Comment by RodrigoLeonMdp** [comment]
Nuevo resultado: 
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/931d5c22-7ffa-499f-b403-679143b9a668)
Quedaria pendiente como manejar los colores de los botones cuando el background color es green o dark-green. Dado que se dificulta verlos.

**Comment by RodrigoLeonMdp** [comment]
Solucionado!
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/c9597dbf-5030-40ba-83a4-74e3ed8522db)
