### ISSUE TITLE
Datocms - modelo congress - campo fecha opcional

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#105]
Ya que vamos a usar la pagina de congress como landing el campo de fecha deberia ser opcional ya que no aplica para landings

1. marca campo como opcional
2. revisar componente que soporte campo fecha opcional

![Captura de pantalla 2023-05-17 a las 12 53 18](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/a6b6ab11-326f-4f03-88d2-dcddeaa725d2)

**Comment by RodrigoLeonMdp** [comment]
Modificado! El campo de fecha lo dejo como REQUERIDO, pero solo se activara si activamos el booleano de 'Is congress':
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/87ddebe2-31ec-4aa4-a6c1-eec7a2e0c6d7)

![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/c1745087-d2ea-4bdc-8827-82de407a0d2d)
