### ISSUE TITLE
Datocms - Gastby - Nueva pagina congress/landing no funciona

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#106]
He creado una nueva pagina congress/landing para ver com funciona como landing pero no funciona en gatsby me da pagina no encontrada

https://egp.admin.datocms.com/editor/item_types/1313556/items/155361892

**Comment by RodrigoLeonMdp** [comment]
En gatbsby-node quitar 'events', en el loop de congress e inner pages

**Comment by RodrigoLeonMdp** [comment]
Solucionado: https://elaborate-frangipane-2705dc.netlify.app/test-landing/
