### ISSUE TITLE
Datocms + gatsby - congress inner page

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#108]
Yo en gatsny-node, le pasaria a congreess inner por contexto solo el id de la pagina padre

congress.map(({ node: congress }) => {
          congress.pages.map((item) => {
            createPage({
              path: `/events/${item.slug}`,
              component: templates.congressInner,
              context: {
                slug: item.slug,
                id: item.id,
                congressTitle: congress.title,
                congressMenu: congress.pages,
                congressSlug: congress.slug,
              },
            });
          });
        });

en lugar de titulo, menu, etc.. 

Luego en congress inner haces query hacia el id padre y te devuelves el titulo, color, ctas (actualmente estan harcodeados en congress inner)

**Comment by RodrigoLeonMdp** [comment]
Modificado, previews:
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/300b1e86-360c-49e3-9c93-cfd933ac6e71)
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/c18008a4-b8cd-474e-82f8-52eac7587ecc)

**Comment by marceltectonica** [comment]
Nada. gestionamos el diseño en la tarea concreta. esto esta hecho
