### ISSUE TITLE
Deskotp - Fecha en las cards de post

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#109]
La fecha que aparece en las cards de Post es la de creacion, deberia ser el campo de date del modelo

![Captura de pantalla 2023-05-19 a las 14 07 26](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/193a8117-34f6-4d1f-85d4-54e066730b33)

**Comment by RodrigoLeonMdp** [comment]
Solucionado!
