### ISSUE TITLE
Desktop - Listado de post

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#110]
1. Deberian ser 12 items por pagina
2. se deberian ordernar en base al campo 'date'

![Captura de pantalla 2023-05-19 a las 14 07 26](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/a467df8f-29ae-48a5-ac4d-a6c2cac02661)

**Comment by RodrigoLeonMdp** [comment]
Solucionado!
