### ISSUE TITLE
Desktop - Links en el contenido del detalle de post

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#111]
Repasar color de los enlaces por defecto, salen en azul ahora:

http://localhost:8000/news/european-greens-podcast-launches/

No se si es el color que se acordo.

**Comment by RodrigoLeonMdp** [comment]
Solucionado! Ahora utiliza el color: --egp-green
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/2ea1188a-b90e-45d6-94ff-286c0cca07df)

**Comment by marceltectonica** [comment]
Podemos concreta si van a querer algun hover en estos enlaces?
