### ISSUE TITLE
revisar blockquotes en proyectos importados

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#114]
En datocms
https://elaborate-frangipane-2705dc.netlify.app/news/6th-european-greens-congress-getting-ready-2024-european-elections/

En origen
https://europeangreens.eu/news/6th-european-greens-congress-getting-ready-2024-european-elections/

Tenemos el campo 'old nid' en datocms que esta informado solo en los casos que son posts importados. Me guardo el id ahi para poder hacer rollbacks luego. 

Usando eso podriamos añadir alguna clase al contenedor del contenido del post para que los blockquotes de muestren de mejor forma.

**Comment by RodrigoLeonMdp** [comment]
He ajustado los blockquotes para que ocupen el 100% del ancho (solo cuando son posts importados o tienen el campo old_nid seteado) del contenedor dado que tienen demasiado contenido, quedarian de la siguiente manera:
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/141e6eb0-fdc4-4bdb-b3ab-7653cdce4584)
