### ISSUE TITLE
Añadir estado a resolutions list filtros

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#41]
Deberiamos usar algun tipo de estado. Pensaba que no haría falta pero si. Si se accede directamente a la pagina con algún filtro aplicado, por ejemplo:

https://elaborate-frangipane-2705dc.netlify.app/green-policies/?type=resolution&

Los checkbox deberian estar marcados a partir de los params de la url, ahora salen sin seleccionar

**Comment by RodrigoLeonMdp** [comment]
@marceltectonica Solucionado aqui: https://github.com/Tectonica-Campaigns-Solutions/ga-egp/pull/43
