### ISSUE TITLE
Comportamiento opcion 'all' en listado de eventos

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#42]
El comportamiento esperadoes que si marco 'all' me selecciones todas la opciones y si demascaro 'all' me las deseleccion todas. 

Por tanto 'all' no formaria parte de las opciones sino que seria un elemento para modificar el estado de los checkbox.

**Comment by RodrigoLeonMdp** [comment]
@marceltectonica Solucionado aqui: https://github.com/Tectonica-Campaigns-Solutions/ga-egp/pull/43
