### ISSUE TITLE
Revisar inputs buscador resolutions

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#44]
Hola, 

Tienes en main como enfocaria yo los radios y checkbox del buscador de resolutions. El input deberia estar escondido, y el label seria todo el boton. Segun si input es checked modificamos el label (faltaria añadir en el label como brackground el falso input como imagen)

input:checked + label{

**Comment by RodrigoLeonMdp** [comment]
@marceltectonica Arreglado aqui (inputs styles y multiple checkbox values): https://github.com/Tectonica-Campaigns-Solutions/ga-egp/pull/46 (Junto con cambios en el componente de Breadcrumb)
