### ISSUE TITLE
Revisar barra blanca extraña en cabecera

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#45]
![Captura de pantalla 2023-02-10 a las 10 45 49](https://user-images.githubusercontent.com/110401825/218059171-d7fb7eb0-71ff-43b1-bf67-e841aa0448a4.png)

**Comment by RodrigoLeonMdp** [comment]
@marceltectonica En el figma se logra ver un border superior blanco
![image](https://user-images.githubusercontent.com/112974289/218078018-51fa67c3-f02f-4022-b376-4a943c681a86.png)

**Comment by marceltectonica** [comment]
Toda la razon.. me parece raro.. lo comento para que me confirmen. Me lo asigno
