### ISSUE TITLE
Revisar warning label for

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#83]
Warning: Invalid DOM property `for`. Did you mean `htmlFor`?

Habria que subtituir cualquier instancia de for= or htmlFor= en los labels

**Comment by RodrigoLeonMdp** [comment]
Se solucionaron varios warnings/errors en el sig. pr: https://github.com/Tectonica-Campaigns-Solutions/ga-egp/pull/85
