### ISSUE TITLE
Desktop - Design - Hero homepage

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#87]
Revisar el ancho y los breakpoints del contenido del hero. 

Esto no deberíaa pasar 

![Captura de pantalla 2023-05-12 a las 8 53 31](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/81bb041e-6074-48b1-9c16-f2bddae2b867)

**Comment by marceltectonica** [comment]
Falta tb el degradado bien hecho de izquieda a derecha como en el diseño y corregir la alineacion vertical de titulo y texto

![Uploading hero-homepage.jpg…]()

**Comment by RodrigoLeonMdp** [comment]
Solucionado!
