### ISSUE TITLE
Desktop - Design - Componente our positions

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#88]
Deberias aclarar con Martina como es el hover de los botones del pasador

![Captura de pantalla 2023-05-12 a las 8 57 51](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/0db24a94-546d-4581-9736-d0f4eea1295e)

**Comment by RodrigoLeonMdp** [comment]
Le deje la consulta a Martina!

**Comment by RodrigoLeonMdp** [comment]
Se agrego un hover basico, segun lo que vi el prototipo de figma.

**Comment by marceltectonica** [comment]
No veo diferencia. Me falta algo?

**Comment by RodrigoLeonMdp** [comment]
Deberia verse de esta manera, al pasar el mouse sobre las flechitas:
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/807078e6-8d37-4ba5-b445-5674b1c7545a)

**Comment by marceltectonica** [comment]
Ahora si

Dale.
