### ISSUE TITLE
Desktop - Design - Modulo campañas

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#89]
Esto deberia estar en dos columnas no uno encima del otro

![Captura de pantalla 2023-05-12 a las 8 58 52](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/9f70ef5a-e223-4561-8c97-123aafb205fc)

**Comment by RodrigoLeonMdp** [comment]
Solucionado!

**Comment by marceltectonica** [comment]
@RodrigoLeonMdp 

Yo revisaria la alineacion horizontal. Comparalo con el diseño no esta igual. 

https://monosnap.com/file/OPVHu1W9Kb0pTqGDqMK4wdSMHv9cME

**Comment by RodrigoLeonMdp** [comment]
Modificado, resultado actual:
![image](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/112974289/fb49a22d-e930-4d2e-9dcf-082cfe88a112)
