### ISSUE TITLE
Desktop - Design - Modulo campañas

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#90]
Podemos confirmar que aqui faltan los ctas porque no estan en contenido? o faltan por añadir al componente?

Web:
![Captura de pantalla 2023-05-12 a las 8 59 48](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/3100deab-4240-41c2-8bdd-503695019e6a)

Diseño:
![Captura de pantalla 2023-05-12 a las 9 00 45](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/34f435fe-2355-4742-b086-266c2cc13bec)

**Comment by RodrigoLeonMdp** [comment]
Solucionado! Faltaba agregar la logica en el componente para soportar links
