### ISSUE TITLE
Desktop - Design - Card update

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#92]
Reduciria un poco espacio superior, revisaria margen izquierdo del titulo y reduciria espacio entre titulo e imagen

Consultaria con Martina o Mar que pasa cuando los titulos tiene diferente tamaño. No tenemos ejemplo. 

![card-post](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/6e29b138-3cf3-4555-a900-a3dbcebcbf9f)

**Comment by RodrigoLeonMdp** [comment]
Solucionado! Ajuste margenes/paddings. Y le deje la consulta a Martina.

**Comment by RodrigoLeonMdp** [comment]
Martina comento que esta bien como lo manejamos, el texto deberia estar abajo y crecer hacia arriba

**Comment by marceltectonica** [comment]
@RodrigoLeonMdp  esto esta para revisar?

**Comment by RodrigoLeonMdp** [comment]
@marceltectonica  Pendiente de solucionar aun!
