### ISSUE TITLE
Desktop - Design - Pagina news

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#93]
Reduciria el espacio en blanco

![Captura de pantalla 2023-05-12 a las 9 12 52](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/a91589e9-19a7-4a84-87b9-38a1142900fd)

**Comment by RodrigoLeonMdp** [comment]
Solucionado!
