### ISSUE TITLE
Desktop - Design - Our positions

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#94]
En resoluciones mas pequeñas de desktop revisaria que no este a 3 columnas sino que salte a 2

![Captura de pantalla 2023-05-12 a las 9 13 58](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/d00a1523-280e-4c41-8ab6-7a44108a58e0)

**Comment by RodrigoLeonMdp** [comment]
Solucionado!

**Comment by marceltectonica** [comment]
@RodrigoLeonMdp 

Creo que falta revisar un poco mas:

![Captura de pantalla 2023-05-14 a las 8 43 55](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/9249a064-4b52-4376-8293-ac34058f9a4f)

**Comment by RodrigoLeonMdp** [comment]
Actualizado!
