### ISSUE TITLE
Desktop - Design - Revisar como deberian ser los links dentro de contenido

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#95]
https://elaborate-frangipane-2705dc.netlify.app/about/

![Captura de pantalla 2023-05-12 a las 9 15 55](https://github.com/Tectonica-Campaigns-Solutions/ga-egp/assets/110401825/f3f7499c-48c6-49c1-bc4a-080e711249ef)

**Comment by RodrigoLeonMdp** [comment]
Solucionado! Los links ahora son de color verde (egp-green)
