### ISSUE TITLE
Desktop - Detail Post 

### ISSUE THREAD

**Issue by marceltectonica** [Tectonica-Campaigns-Solutions/ga-egp#98]
1. La fecha deberia estar en font weight 400

2. Si no hay autores la imagen y el contenido no deberian estar pegados (inicialmente no tendran autores)
http://localhost:8888/news/europe-day-europe-must-go-green/

3. El título no deberia ser todo el ancho sino un ancho maximo 

4. Añadir el breadcrumb (deberiamos conseguir la ruta completa a 'News' para construirlo)

5. Repasaria espaciados de la cabecera no acaben de estar como el diseño

6. La flor de fondo en el detalle de post creo que es otro asset, la veo mas oscuar en el diseño

**Comment by RodrigoLeonMdp** [comment]
Pendiente de hacer news linkeable en el breadcrumb @marceltectonica
